### PR TITLE
Addition of `tiledb.DictionaryFilter`

### PR DESCRIPTION
**Pull request by nguyenv**
* Wraps around TILEDB_FILTER_DICTIONARY (https://github.com/TileDB-Inc/TileDB/pull/3042)

### CODE REVIEW

**Review by ihnorton — APPROVED** [review]
LGTM but please add a test or use in an exising test.

**Comment by nguyenv** [comment]
> LGTM but please add a test or use in an exising test.

https://github.com/TileDB-Inc/TileDB-Py/pull/1074/files#diff-b5f1238040c8e028f6c547909a2b8ac4ad25ee0e10f45946fc5d6eca7bc5fa6bR55

It is tested in here unless you'd like me to add another test.

**Comment by ihnorton** [comment]
Yes - please use it in some test that actually writes data too (those just test initialization). eg one of the string array tests.

**Comment by nguyenv** [comment]
> Yes - please use it in some test that actually writes data too (those just test initialization). eg one of the string array tests.

I have just updated the PR with [this](https://github.com/TileDB-Inc/TileDB-Py/pull/1074/files#diff-b5f1238040c8e028f6c547909a2b8ac4ad25ee0e10f45946fc5d6eca7bc5fa6bR89-R106) test. Please let me know if this is what you're looking for.

**Review by ihnorton — APPROVED** [review]
LGTM, thanks

**Pull request merged**
