### PR TITLE
Allow delete mode for attributes on dense arrays

### PR DESCRIPTION
**Pull request by johnkerl**
Needs unit-test coverage

### CODE REVIEW

**Comment by nguyenv** [comment]
Closing as query conditions are not supported for dense arrays.

**Comment by johnkerl** [comment]
@nguyenv do we not want to support delete-by-attribute filter for dense arrays?

**Comment by nguyenv** [comment]
Oh that's a good point. We should support it for attributes. I'll reopen the PR.

**Comment by kounelisagis** [comment]
Query deletes aren't supported for dense arrays in core. Will reopen if needed.

**Pull request closed without merging**
