### PR TITLE
0.26.1 against TileDB 2.20.1

### PR DESCRIPTION
**Pull request by ihnorton**
Release 0.26.1 against TileDB 2.20.1

### CODE REVIEW

**Comment by ihnorton** [comment]
Windows build is blocked by https://github.com/TileDB-Inc/TileDB/pull/4759

**Comment by dudoslav** [comment]
Build passed locally for me so I approve

**Review by dudoslav — APPROVED** [review]
I did build windows wheels locally:

```
02/28/2024  01:56 PM         8,165,644 tiledb-0.26.1.dev4-cp310-cp310-win_amd64.whl
02/28/2024  01:57 PM         8,164,559 tiledb-0.26.1.dev4-cp311-cp311-win_amd64.whl
02/28/2024  01:57 PM         8,159,622 tiledb-0.26.1.dev4-cp312-cp312-win_amd64.whl
02/28/2024  01:42 PM         8,189,745 tiledb-0.26.1.dev4-cp36-cp36m-win_amd64.whl
02/28/2024  01:55 PM         8,154,482 tiledb-0.26.1.dev4-cp37-cp37m-win_amd64.whl
02/28/2024  01:55 PM         8,178,752 tiledb-0.26.1.dev4-cp38-cp38-win_amd64.whl
02/28/2024  01:56 PM         8,162,826 tiledb-0.26.1.dev4-cp39-cp39-win_amd64.whl
```

**Comment by ihnorton** [comment]
Release check:
```
In [1]: import tiledb, numpy as np, time

In [2]: tiledb.version(), tiledb.libtiledb.version()
Out[2]: ((0, 26, 1), (2, 20, 1))

In [3]: tiledb.default_ctx(tiledb.cloud.Ctx().config())
Out[3]: tiledb.Ctx() [see Ctx.config() for configuration]

In [4]: a = tiledb.open("tiledb://TileDB-Inc/645a08a0-aafc-4298-be69-17f8e368bc67")

In [5]: a.schema
Out[5]:
ArraySchema(
  domain=Domain(*[
    Dim(name='image_id', domain=(0, 18446744073709541615), tile=10, dtype='uint64', filters=FilterList([ZstdFilter(level=-1), ])),
    Dim(name='d1', domain=(0, 223), tile=224, dtype='uint64', filters=FilterList([ZstdFilter(level=-1), ])),
    Dim(name='d2', domain=(0, 223), tile=224, dtype='uint64', filters=FilterList([ZstdFilter(level=-1), ])),
    Dim(name='d3', domain=(0, 2), tile=2, dtype='uint64', filters=FilterList([ZstdFilter(level=-1), ])),
  ]),
  attrs=[
    Attr(name='value', dtype='uint8', var=False, nullable=False, enum_label=None),
  ],
  cell_order='row-major',
  tile_order='row-major',
  sparse=False,
)

In [6]: b = tiledb.open("s3://tiledb-isaiah2/debug/a1")

In [7]: b.schema
Out[7]:
ArraySchema(
  domain=Domain(*[
    Dim(name='__dim_0', domain=(0, 3), tile=4, dtype='uint64', filters=FilterList([ZstdFilter(level=-1), ])),
    Dim(name='__dim_1', domain=(0, 3), tile=4, dtype='uint64', filters=FilterList([ZstdFilter(level=-1), ])),
  ]),
  attrs=[
    Attr(name='', dtype='float64', var=False, nullable=False, enum_label=None),
  ],
  cell_order='row-major',
  tile_order='row-major',
  sparse=False,
)
```

**Pull request merged**
