### PR TITLE
Finish pybind11 conversion

### PR DESCRIPTION
**Pull request by kounelisagis**
This PR merges the `pybind11` branch into `dev`, removing the dependency on Cython.

Benchmarks (in seconds):

| Metric   | Before Merge (dev branch) | After Merge (pybind11-full) | Percentage Difference |
|----------|---------------------------|-----------------------------|-----------------------|
| **Real** | 81.74 avg                 | 84.28 avg                  | +3.11%               |
| **User** | 64.91 avg                 | 67.15 avg                  | +3.45%               |
| **Sys**  | 56.40 avg                 | 58.25 avg                  | +3.28%               |

---

[sc-59525]

### CODE REVIEW

**Comment by kounelisagis** [comment]
- Pending latency benchmarking.
- Reminder: Do not squash merge to preserve the commit history.

**Review by nguyenv — APPROVED** [review]
This is amazing work! So great to see everything in Pybind11 now.

**Comment by johnkerl** [comment]
+1 on that -- thank you  @kounelisagis !! 😎

**Review by ihnorton — APPROVED** [review]
🎉

**Pull request merged**
