### PR TITLE
Add ability to pass shape tuple to empty_like 

### PR DESCRIPTION
**Pull request by ocsmit**
Hopefully addresses #1315

### CODE REVIEW

**Comment by ihnorton** [comment]
Thanks for the PR @ocsmit! I've enabled CI to run through here and @nguyenv will take a look ASAP.

**Comment by ocsmit** [comment]
Thanks!

**Comment by ocsmit** [comment]
No problem, just added! Let me know if the type checking for the shape tuple needs to be more robust as well.

**Comment by nguyenv** [comment]
> No problem, just added! Let me know if the type checking for the shape tuple needs to be more robust as well.

Thanks! And no, I think the checking in `schema_like` should be sufficient.

**Pull request merged**
