### PR TITLE
CI for mac and win (WIP) on Azure pipelines

### PR DESCRIPTION
**Pull request by ihnorton**
includes and closes #97 
fixes #98

### CODE REVIEW

**Comment by ihnorton** [comment]
WIP on Windows because TileDB and TileDB-Py both build, but tests currently fail because it can't load the DLL. Probably a path/install issue, but debugging on CI isn't really efficient so I'll debug on my Windows laptop at home.

**Comment by ihnorton** [comment]
Success on mac: https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=2

**Comment by ihnorton** [comment]
Ok, Windows build and install is succeeding here, and tests are running. There are several test failures I will have to dig into on laptop, but as far as build and CI this is just waiting on https://github.com/TileDB-Inc/TileDB/pull/1125 and 1126. Once that is done I will squash the commits.

**Comment by jakebolewski** [comment]
Hmm, the returning a different coordinate dtype error is strange on Windows, and the group comparison probably needs some Win. specific changes.    Otherwise LGTM.

**Comment by ihnorton** [comment]
> returning a different coordinate dtype error is strange on Windows

https://github.com/numpy/numpy/issues/9464 🤷‍♂️ ... Fixed in latest commit by using `np.int64`.

> and the group comparison probably needs some Win. specific changes

Yes: fixed by normalizing path so that the comparison succeeds (the internal path was using fwd slash.

CI passed on both platforms: https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=12

**Pull request merged**
