### PR TITLE
Add ruff linter

### PR DESCRIPTION
**Pull request by gsakkis**
https://github.com/charliermarsh/ruff

### CODE REVIEW

**Comment by ihnorton** [comment]
Is there something from isort that ruff can't do? https://github.com/charliermarsh/ruff#isort-i

**Comment by ihnorton** [comment]
I'm inclined to just use one tool. Thanks.

**Comment by gsakkis** [comment]
Would be nice to merge this to prevent further conflicts as it touches most files.

**Review by ihnorton — APPROVED** [review]

**Comment by ihnorton** [comment]
Thanks

**Pull request merged**
