### PR TITLE
[2.18.0] Add Group Metadata Consolidation and Vacuuming

### PR DESCRIPTION
**Pull request by nguyenv**
Depends on https://github.com/TileDB-Inc/TileDB/pull/4412. Will be available in 2.18.0.

**Changes**
- Addition of `Group.consolidate_metadata` and `Group.vacuum_metadata`
- Move unit tests that do not test group metadata from `GroupMetadataTest` to `GroupTestCase`

### CODE REVIEW

**Comment by nguyenv** [comment]
[sc-34410]

**Comment by nguyenv** [comment]
`nullptr` issue has been fixed by [#4412](https://github.com/TileDB-Inc/TileDB/pull/4412). Awaiting release 2.17.2.

**Review by ihnorton — APPROVED** [review]
LGTM, pending tests

**Comment by nguyenv** [comment]
Cherry picked to https://github.com/TileDB-Inc/TileDB-Py/pull/1869.

**Pull request closed without merging**
