### PR TITLE
Add Rich Display for Various TileDB Objects in Jupyter Notebook

### PR DESCRIPTION
**Pull request by nguyenv**

### CODE REVIEW

**Comment by nguyenv** [comment]
reprhtml

**Review by ihnorton — CHANGES_REQUESTED** [review]
Could you please left-justify the (key, value) table listings, eg for fragment info in the first screenshot? I think that better matches what I've seen for other HTML rendering, and it should be easier to read when the column is widened by a path.

**Comment by ihnorton** [comment]
> when the column is widened by a path

Could potentially truncate long URIs in the future, and show the full thing on hover only.

**Comment by ihnorton** [comment]
cc @jp-dark

**Review by ihnorton — APPROVED** [review]

**Pull request merged**
